// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh8lug7zuZfGXaSjBhyXPGxwP19mk55Uk',
    appId: '1:1070373116243:web:8145fb31381b7c8a23a9a6',
    messagingSenderId: '1070373116243',
    projectId: 'move-up-896e9',
    authDomain: 'move-up-896e9.firebaseapp.com',
    storageBucket: 'move-up-896e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaIcG6wnKfJtPkXlzk5RL69lm37dddx0E',
    appId: '1:1070373116243:android:7d18aa4ed95c2c6b23a9a6',
    messagingSenderId: '1070373116243',
    projectId: 'move-up-896e9',
    storageBucket: 'move-up-896e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfCpyZg0vKKQKEGkblUhlKm2S6aOjuuY',
    appId: '1:1070373116243:ios:6fabdfeadc782ff523a9a6',
    messagingSenderId: '1070373116243',
    projectId: 'move-up-896e9',
    storageBucket: 'move-up-896e9.firebasestorage.app',
    iosBundleId: 'com.example.moveUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPfCpyZg0vKKQKEGkblUhlKm2S6aOjuuY',
    appId: '1:1070373116243:ios:6fabdfeadc782ff523a9a6',
    messagingSenderId: '1070373116243',
    projectId: 'move-up-896e9',
    storageBucket: 'move-up-896e9.firebasestorage.app',
    iosBundleId: 'com.example.moveUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh8lug7zuZfGXaSjBhyXPGxwP19mk55Uk',
    appId: '1:1070373116243:web:94dd5764426d14da23a9a6',
    messagingSenderId: '1070373116243',
    projectId: 'move-up-896e9',
    authDomain: 'move-up-896e9.firebaseapp.com',
    storageBucket: 'move-up-896e9.firebasestorage.app',
  );
}
